### ISSUE TITLE
Where to find a sample from "Staged WordPress Deployments"

### ISSUE THREAD

**Issue by xperiandri** [azureappserviceoss/wordpress-azure#1]
@SunBuild, where to find a sample from your video [Staged WordPress Deployments on Azure with Sunitha Muthukrishna](https://channel9.msdn.com/Shows/Azure-Friday/Staged-WordPress-Deployments-on-Azure-with-Sunitha-Muthukrishna)?

In particular a config data selection is interesting

**Comment by azureappserviceoss** [comment]
here is a sample .https://github.com/SunBuild/wordpressazure .Note the wordpress version is outdated though the process is the same
