### ISSUE TITLE
Unable to edit WordPress Address and Site Address in WordPress Admin portal

### ISSUE THREAD

**Issue by MattTato** [azureappserviceoss/wordpress-azure#26]
I have tried to install the WordPress gallery application twice using two different SQL types, MySQL In App and the Azure Database for MySQL (Preview), but with both basic installations, I'm unable to edit the URLs for my site. I want to update them to be my custom domain, but the boxes are grayed out.

![image](https://user-images.githubusercontent.com/6508715/28755522-a07b0cde-7522-11e7-9ab7-f3ce21bc7c37.png)

I can edit them in the wp-config.php file instead, but I'd prefer to not do that.

**Comment by Song2017** [comment]
@MattTato 

- Please find **wp-config.php**( eg, /home/site/wwwroot) 
- comment **define('WP_HOME'..**,**define('WP_SITEURL'..**
- at last, we would edit that
![image](https://user-images.githubusercontent.com/16848896/28762952-176f5348-75ed-11e7-9390-0341aa771fcf.png)

**Comment by MattTatoczenko** [comment]
I had to comment out this section in the wp-config.php:
![image](https://user-images.githubusercontent.com/24440502/28780492-86431884-75cc-11e7-865d-464d8a5111f7.png)

While I don't swap slots, I wanted to see if this will negatively impact my site at all.
