### ISSUE TITLE
Where is azuredeploy.parameters.json?

### ISSUE THREAD

**Issue by gfilicetti** [azureappserviceoss/wordpress-azure#27]
Hi guys,

I noticed in the template there a "repoUrl" parameter, but we can't figure out where this comes from. Clicking on the deploy button brings us to the deploy screen but we aren't prompted for the repoUrl.

We're assuming this url points to the wordpress source files that get deployed into the Webapp.

**Comment by Song2017** [comment]
How it works
When a user clicks on the button, a “referrer” header is sent to azuredeploy.net which contains the location of the Git repository to deploy from. If you would like to host the button somewhere outside of your Git repository, you can specify a query string in the target URL like so: 
```
<a href="https://azuredeploy.net/?repository=https://github.com/user/repo" target="_blank">
    <img src="http://azuredeploy.net/deploybutton.png"/>
</a>
````
