### ISSUE TITLE
Increase maximum size of media uploads?

### ISSUE THREAD

**Issue by nor0x** [azureappserviceoss/wordpress-azure#28]
Currently playing around with "Wordpress on Linux" in Azure. I was wondering how we can increase the maximum filesize of media uploads. Currently it's limited to 2MB. I've tried several methods to increase the maximum upload size via `post_max_size`, `upload_max_filesize` and `memory_limit` in:
- php.ini
- user.ini
- functions.php

Anybody can help me out with this issue?

**Comment by Song2017** [comment]
php.ini has access limit, so we use .user.ini.

1. access you [kudu](https://blogs.msdn.microsoft.com/benjaminperkins/2014/03/24/using-kudu-with-windows-azure-web-sites/) url: https://<your site>.scm.azurewebsites.net/DebugConsole 
2. touch [.user.ini](http://www.php.net/manual/en/configuration.file.per-user.php)
3. add this to .user.ini
```
post_max_size=60M
upload_max_filesize=20M
; http://php.net/manual/en/info.configuration.php#ini.max-input-time
max_input_time=300
```
4. stop/start wordpress

**Comment by nor0x** [comment]
just tried adding the `.user.ini` file and restarting wordpress. Unfortunately it doesn't work for me. Still limited to 2MB
<img width="698" alt="screenshot at aug 09 11-44-14" src="https://user-images.githubusercontent.com/3210391/29115831-33be8ba0-7cf9-11e7-976b-9445f46e9856.png">

**Comment by Song2017** [comment]
may you try to stop/start web app on portal?
![image](https://user-images.githubusercontent.com/16848896/29116205-aec446cc-7d2c-11e7-80fe-2ea103ded29f.png)

**Comment by nor0x** [comment]
Yes - I started/stopped the web app several times now. Still limited
<img width="706" alt="screenshot at aug 09 12-07-08" src="https://user-images.githubusercontent.com/3210391/29116512-4cb60640-7cfb-11e7-97b7-275ca5fd3906.png">

**Comment by Song2017** [comment]
let's print php info
1. touch phpinfo.php in /home/site/wwwroot
```
<?
phpinfo();
```
2. access your site: http://</your-site/>.azurewebsites.net/phpinfo.php
3. then please find parameter: post_max_size, upload_max_filesize, max_input_time and verify whether changes works

**Comment by nor0x** [comment]
phpinfo still prints the old values:
![screenshot at aug 09 14-35-25](https://user-images.githubusercontent.com/3210391/29121730-0fb5487c-7d10-11e7-8eb4-3fcaefd2a943.png)

**Comment by Song2017** [comment]
It makes no sense. 
Does parameter in php.ini and functions.php be restored or other customized modification
I can not repro this issue. A version updated should work

**Comment by nor0x** [comment]
The only modification i made was moving the Wordpress installation to a separate folder inside wwwroot. It seems that the added .user.ini file does not get parsed by php
<img width="940" alt="screenshot at aug 09 16-25-10" src="https://user-images.githubusercontent.com/3210391/29126721-6fd92020-7d1f-11e7-93b5-1737da4f16b2.png">

**Comment by nor0x** [comment]
Solved it!
I used the `.htaccess` file in the `wwwroot` folder and added these two lines

```
php_value post_max_size 20M
php_value upload_max_filesize 20M
```

finally working! -closed

**Comment by fleed** [comment]
Related beginner question: how do I edit files in SSH under Azure app service? couldn't recognize any command to edit files

**Comment by andlewis** [comment]
@fleed "nano" works well
