### ISSUE TITLE
Why relative WP_CONTENT_URL?

### ISSUE THREAD

**Issue by ehausen** [azureappserviceoss/wordpress-azure#30]
I'm wondering why this has to be in the config file?
https://github.com/azureappserviceoss/wordpress-azure/blob/ce5fd8fb2bb3d13126c2fc39cf0e8a2a1401e868/wp-config.php#L102-L106

Especially I'm wondering  about the 
https://github.com/azureappserviceoss/wordpress-azure/blob/ce5fd8fb2bb3d13126c2fc39cf0e8a2a1401e868/wp-config.php#L105
Why does WP_CONTENT_URL have to be defined relative? This breaks a certain caching plugin. Disabling this line fixes problem of referring a cache files and does not seem to harm.

The normal is `define( ‘WP_CONTENT_URL’, get_option(‘siteurl’) . ‘/wp-content’);`

**Comment by azureappserviceoss** [comment]
The repository is used for Azure web apps [ windows ] . Web apps has a feature called deployment slots and using relative path makes it easier to swap your code from a deployment slot to production slot without making any database changes  in wordpress.
